version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - pip install -r Test/requirements.txt
      - mkdir -p test-reports
  build:
    commands:
      - pytest --html=test-reports/report.html --self-contained-html Test
      - echo Finish Code Test
  post_build:
    commands:
      - sam package --output-template-file Build/StaggingBuild.yaml --s3-bucket codepipeline-ap-southeast-1-92287412452
      - sam deploy  --template-file Build/StaggingBuild.yaml --stack-name crud --capabilities CAPABILITY_IAM --region ap-southeast-1
      - echo Build completed on `date`

artifacts:
 files:
   - packaged.yml

reports:
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml
