version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - pip install -r Test/requirements.txt
      - mkdir -p test-reports
  build:
    commands:
      - pytest --html=test-reports/report.html --self-contained-html Test
  post_build:
    commands:
      - echo Build completed on `date`
  
reports:
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml
