version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11zt23stfa07h"
s3_prefix = "crud"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "LambdaVersion=\"1.0\" Enviroment=\"Prod\""
